/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5XJEp9ecxgT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Component() {
  return (
    (<section className="w-full py-12 md:py-24 lg:py-32 dark">
      <div className="container space-y-8 px-4 md:px-6">
        <div className="text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Portfolio</h2>
          <p
            className="mx-auto max-w-[700px] text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Check out some of the projects I've worked on.
          </p>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          <div
            className="group overflow-hidden rounded-lg shadow-lg transition-all hover:scale-[1.02] hover:shadow-xl">
            <Link className="block" href="#">
              <img
                alt="Project 1"
                className="h-60 w-full object-cover object-center transition-all group-hover:scale-105"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300" />
              <div className="bg-gray-800 p-4">
                <h3 className="text-lg font-semibold text-gray-50">Project 1</h3>
                <p className="text-sm text-gray-400">A brief summary of Project 1.</p>
              </div>
            </Link>
          </div>
          <div
            className="group overflow-hidden rounded-lg shadow-lg transition-all hover:scale-[1.02] hover:shadow-xl">
            <Link className="block" href="#">
              <img
                alt="Project 2"
                className="h-60 w-full object-cover object-center transition-all group-hover:scale-105"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300" />
              <div className="bg-gray-800 p-4">
                <h3 className="text-lg font-semibold text-gray-50">Project 2</h3>
                <p className="text-sm text-gray-400">A brief summary of Project 2.</p>
              </div>
            </Link>
          </div>
          <div
            className="group overflow-hidden rounded-lg shadow-lg transition-all hover:scale-[1.02] hover:shadow-xl">
            <Link className="block" href="#">
              <img
                alt="Project 3"
                className="h-60 w-full object-cover object-center transition-all group-hover:scale-105"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300" />
              <div className="bg-gray-800 p-4">
                <h3 className="text-lg font-semibold text-gray-50">Project 3</h3>
                <p className="text-sm text-gray-400">A brief summary of Project 3.</p>
              </div>
            </Link>
          </div>
          <div
            className="group overflow-hidden rounded-lg shadow-lg transition-all hover:scale-[1.02] hover:shadow-xl">
            <Link className="block" href="#">
              <img
                alt="Project 4"
                className="h-60 w-full object-cover object-center transition-all group-hover:scale-105"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300" />
              <div className="bg-gray-800 p-4">
                <h3 className="text-lg font-semibold text-gray-50">Project 4</h3>
                <p className="text-sm text-gray-400">A brief summary of Project 4.</p>
              </div>
            </Link>
          </div>
          <div
            className="group overflow-hidden rounded-lg shadow-lg transition-all hover:scale-[1.02] hover:shadow-xl">
            <Link className="block" href="#">
              <img
                alt="Project 5"
                className="h-60 w-full object-cover object-center transition-all group-hover:scale-105"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300" />
              <div className="bg-gray-800 p-4">
                <h3 className="text-lg font-semibold text-gray-50">Project 5</h3>
                <p className="text-sm text-gray-400">A brief summary of Project 5.</p>
              </div>
            </Link>
          </div>
          <div
            className="group overflow-hidden rounded-lg shadow-lg transition-all hover:scale-[1.02] hover:shadow-xl">
            <Link className="block" href="#">
              <img
                alt="Project 6"
                className="h-60 w-full object-cover object-center transition-all group-hover:scale-105"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300" />
              <div className="bg-gray-800 p-4">
                <h3 className="text-lg font-semibold text-gray-50">Project 6</h3>
                <p className="text-sm text-gray-400">A brief summary of Project 6.</p>
              </div>
            </Link>
          </div>
        </div>
      </div>
    </section>)
  );
}
